//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppC
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public int STT { get; set; }
        public string fullname { get; set; }
        public string thon { get; set; }
        public string matram { get; set; }
        public string dong { get; set; }
        public string pha { get; set; }
        public string mahieucongto { get; set; }
        public System.DateTime ngaykiemdinh { get; set; }
        public System.DateTime hankiemdinh { get; set; }
        public string ghichu { get; set; }
    }
}
